### ISSUE TITLE
Does not open in Illustrator 19.1 (CC 2015)

### ISSUE THREAD

**Issue by rgbjoy** [GreyRook/Draw2Script#8]
I go to window > extensions > Draw2Script

Nothing happens. Why can't this be installed through the manager?

**Comment by mikebarkmin** [comment]
It can't be installed through the manager, because:

Extension Manager has been discontinued. The lastest release will only work with Adobe CC 2014. When you own Adobe CC 2015 you must install Draw2Script manually. See Announcement: Extension Manager End of Life Notification https://s3.amazonaws.com/cssdk/2015-05-22_TechPartners.html

Do you use Mac or Windows? Only the menu entry is showing, but no window appears? 

I hope we can find a solution.

**Comment by b-g** [comment]
+1 Same here ...  only the menu entry is showing, but no window appears. OSX 10.10.4, Adobe CC 2015. Any hints?

**Comment by mikebarkmin** [comment]
Today we released Draw2Script in the Adobe Add-on Store. Please use the store to install Draw2Script.
- Visit Adobe Add-ons https://creative.adobe.com/addons/products/12429
- Click install
- Draw2Script should be copied to your local drive via the Creative Cloud Desktop App
- If you encounter problems visit https://www.adobeexchange.com/resources/19

If the problems are still occurring, please write back to me.
